AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS SageMaker Endpoint'
Parameters:
  BucketName:
    Description: Name of data bucket
    MaxLength: '64'
    MinLength: '1'
    Type: String
  CommitID:
    Description: ID of the current commit
    MaxLength: '64'
    MinLength: '1'
    Type: String
  SageMakerRole:
    Description: Name of SageMaker role
    MaxLength: '64'
    MinLength: '1'
    Type: String
  StackName:
    Description: Name of pipeline stack
    MaxLength: '64'
    MinLength: '1'
    Type: String
Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub ${AWS::StackName}-${CommitID}
      ExecutionRoleArn: !Sub ${SageMakerRole}
      PrimaryContainer:
        ModelDataUrl: !Sub s3://${BucketName}/${StackName}-${CommitID}/output/model.tar.gz
        Image: 811284229777.dkr.ecr.us-east-1.amazonaws.com/image-classification:latest
  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    DependsOn: EndpointConfig
    Properties:
      EndpointName: !Sub ${AWS::StackName}-${CommitID}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    DependsOn: Model
    Properties:
        EndpointConfigName: !Sub ${AWS::StackName}-${CommitID}
        ProductionVariants:  
        - ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic
          InitialInstanceCount: 1
          InstanceType: ml.t2.medium
          InitialVariantWeight: 1